Lab1 Nachinkin Mikhail P3306
Lisi4ka59/OS pull request #1
Opened 2024-10-22 22:36 UTC by Lisi4ka59

P3306 Начинкин Михаил Анатольевич
Базовый трек, оценка . ЛР 1. Shell
Вариант: Linux, ema-search-str, short-path

## Описание изменений

Реализовал Shell в директории shell
Реализовал программы-нагрузчики в директории benchmark

2024-10-23 14:53 UTC, vityaman requested changes
- [ ] Построить Flamegraph для бэнчей.
- [ ] bpftrace скрипт считающий сколько байт мы прочитали из файла.
- [ ] Обработать ошибки из сисколлов.
- [ ] Расширить shell, добавить способ поставить текущий процесс на паузу и возобновить.
- [ ] Page Cache не очень подробно, как происходит системный вызов, что такое ОС, процессы, потоки, IPC (способы, примеры сисколлов, которые для нужны).

Знать, как оно работает под капотом.

2024-10-23 14:53 UTC, vityaman commented on shell/main.c
> +        perror("Fork failed");
А как получить подробности ошибки? Вопросик для защиты.

2024-10-23 14:53 UTC, vityaman commented on shell/main.c
> +	gettimeofday(&start, NULL);
Поресерчить, а действительно ли ок использовать это для бэнчмаркинга? Достато ли точное время?

2024-10-23 14:53 UTC, vityaman commented on shell/main.c
> +    while (1) {
А можно true, кстати.

2024-10-23 14:53 UTC, vityaman commented on shell/main.c
> +        }
Можно было бы отблить юзер фредли ошибочку.

2024-10-23 14:53 UTC, vityaman commented on shell/main.c
> +        }
Это точно нужно? Без этого не будет работать?

2024-10-23 14:53 UTC, vityaman commented on benchmark/ema-search-str.c
> +            total_bytes_read = overlap;
Можно еще докомпозировать и понизить цикломатическую сложность.

2024-10-23 14:53 UTC, vityaman commented on benchmark/ema-search-str.c
> +    int fd = open(filename, O_RDONLY);
А что с кэшированием? Кто его делает, зачем и как это кэширование конфигурировать?

2024-10-23 14:53 UTC, vityaman commented on benchmark/ema-search-str.c
> +        lseek(fd, 0, SEEK_SET); // Сброс указателя файла в начало
Ошибка может вернуться.

2024-10-23 14:53 UTC, vityaman commented on benchmark/ema-search-str.c
> +        while ((bytes_read = read(fd, buffer + total_bytes_read, BUFFER_SIZE)) > 0) {
В каких случаях вернется меньше чем просили (из-за чего)?

2024-10-23 14:53 UTC, vityaman commented on benchmark/ema-search-str.c
> +void search_substring(const char *filename, const char *substring, int repetitions) {
С помощью утилиты perf можно строить flamegraph. Хочется его построить.

2024-10-24 20:04 UTC, vityaman commented
Давайте еще оформим MR в соответствии с требованиями: https://github.com/secs-dev/os-course/blob/main/doc/code-review.md (обновить заголовок).

2024-10-25 14:18 UTC, Lisi4ka59 commented on shell/main.c
> +        perror("Fork failed");
`perror(explain_fork());`

2024-10-26 08:45 UTC, Lisi4ka59 commented on benchmark/ema-search-str.c
> +        while ((bytes_read = read(fd, buffer + total_bytes_read, BUFFER_SIZE)) > 0) {
Может быть, пока мы читали файл, был подан сигнал прерывания чтения (SIGINT), либо могла закончится память, либо какой-нибудь негодяй мог удалить файл, пока мы его читали

2024-10-26 15:48 UTC, vityaman approved these changes

2024-10-26 17:52 UTC, merged